### ISSUE TITLE
What do you think of is the main similarity and difference between your work and another BEVFusion(by MIT)?

### ISSUE THREAD

**Issue by FrontierBreaker** [ADLab-AutoDrive/BEVFusion#46]
Thanks for your great work! I have a question: what do you think of is the main similarity and difference between your work and another BEVFusion? I also would like to know why bev-based fusion is a good schema for fusion-based perception and what makes for its success? Thanks!!

**Comment by tingtingliangvs** [comment]
Hi, thanks for your attention and insightful question.
1. We both choose the BEV feature space to fuse the features of the two modalities, and both choose LSS as the camera feature extractor. MIT-BEVFusion proposes a high-performance multi-task model that achieves remarkable results in 3D detection and MAP semantic segmentation. Our work focuses on the robustness of the multimodal framework, and more work is done on the framework's compatibility with different models and robustness to sensor failures.
2. Since in autonomous driving scenarios, most of the objects of interest are on the same level, such as a non-flying car, the importance of z-axis features is relatively low. The BEV feature compresses the z-axis feature to the channel dimension, allowing the model to focus on the perception area of the horizontal plane for more efficient 3D detection.
The above is my personal opinion, welcome to discuss and share your views.

**Comment by FrontierBreaker** [comment]
Thanks!
